apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: q1-nginx-replicaset

spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-final

  template:
    metadata:
      name: nginx-final
      labels:
        app: nginx-final

    spec:
      containers:
        - name: nginx-final-container
          image: nginx:1.25
          ports:
            - containerPort: 80
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "<h1>$(hostname)</h1>" > /usr/share/nginx/html/index.html
              nginx -g 'daemon off;'
